# Example: Artistic blend with custom weights
# Creates an artistic effect by heavily weighting wave distortion

effect:
  type: composite
  max_stretch: 0.4
  stretch_curve: ease_out
  start_stretch: 0.05
  end_stretch: 0.5
  effects:
    - type: wave
      wave_amplitude: 0.25
      wave_frequency: 1.5
      wave_phase_speed: 0.15
    - type: wave  # Yes, you can use the same effect type multiple times!
      wave_amplitude: 0.1
      wave_frequency: 5.0
      wave_phase_speed: -0.3  # Negative for opposite direction
      wave_phase_shift: 1.57  # Ï€/2 phase shift
    - type: bias
      stretch_bias: -0.2  # Slight upward tendency
  weights: [0.6, 0.3, 0.1]  # Multiple waves create complex patterns

animation:
  frames: 90
  fps: 30
  interpolation: bilinear
  temporal_smoothing: 0.5  # Heavy smoothing for fluid motion
  upscale: 3
  cumulative: false

output:
  format: mp4
  codec: libx264