# Example configuration for melting effect
# Note: In cumulative mode, the stretch values compound over time
# Use smaller values (0.3-0.6) for subtle effects, larger for dramatic melting
effect:
  type: bias
  max_stretch: 0.2
  stretch_curve: linear
  stretch_bias: 0.15 # Slight downward bias for melting
  start_stretch: 0.0
  end_stretch: 0.2 # Total accumulated stretch by the end
  seed: 42

animation:
  frames: 90
  fps: 30
  interpolation: nearest
  temporal_smoothing: 0.3
  upscale: 3
  cumulative: true # Cumulative for progressive melting
  frame_generator: cumulative

output:
  format: mp4
  codec: libx264
