# Example: All three effects combined
# Creates a complex animation with pivot, wave, and bias effects

effect:
  type: composite
  max_stretch: 0.7
  stretch_curve: linear
  start_stretch: 0.1
  end_stretch: 0.9
  seed: 12345
  effects:
    - type: pivot
      pivot: bottom  # Stretch from bottom
    - type: wave
      wave_amplitude: 0.1
      wave_frequency: 4.0
      wave_phase_speed: 0.2
      wave_phase_shift: 0.5  # Phase offset for variety
    - type: bias
      stretch_bias: 0.3  # Slight downward tendency
  weights: [0.5, 0.3, 0.2]  # 50% pivot, 30% wave, 20% bias

animation:
  frames: 120
  fps: 60  # High framerate for smooth animation
  interpolation: bilinear
  temporal_smoothing: 0.3
  upscale: 2
  cumulative: true  # Cumulative for evolving distortion

output:
  format: mp4
  codec: libx264
  quality: 95