# Combined melting effect with ripple
# Uses cumulative mode to build up the melting effect over time
# The composite effect combines bias (melting) with wave (ripple)
# Now with per-effect stretch curves!

effect:
  type: composite
  max_stretch: 0.2 # Increased slightly to accommodate both effects
  stretch_curve: linear # This controls the overall animation progression
  start_stretch: 0.0
  end_stretch: 0.2
  effects:
    # Melting effect (bias) - progressively stronger
    - type: bias
      stretch_bias: 0.15 # Downward bias for melting
      stretch_curve: linear # Progressive melting over time
    # Ripple effect (wave) - constant strength
    - type: wave
      wave_amplitude: 0.1 # Smaller amplitude for subtle ripple
      wave_frequency: 2.0 # Higher frequency for tighter ripples
      wave_phase_speed: 0.2 # Animated ripple movement
      stretch_curve: constant # Constant ripple strength throughout animation
  weights: [0.8, 0.1] # 70% melting, 30% ripple
  seed: 42

animation:
  frames: 200
  fps: 30
  interpolation: bilinear # Smooth interpolation for fluid motion
  temporal_smoothing: 0.4 # Smoothing to blend the effects nicely
  upscale: 4
  cumulative: true # Essential for progressive melting effect
  frame_generator: cumulative

output:
  format: mp4
  codec: libx264
