# Example configuration for wave-based animation
effect:
  type: wave
  max_stretch: 0.2
  wave_amplitude: 0.3
  wave_frequency: 1.5
  wave_phase_shift: 0.0
  wave_phase_speed: 1.5
  seed: 42

animation:
  frames: 120
  fps: 20
  interpolation: bilinear
  temporal_smoothing: 0.6
  upscale: 3
  cumulative: false
  frame_generator: standard

output:
  format: mp4
  codec: libx264
